/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Cars } from "./Cars";
import { CarsCountArgs } from "./CarsCountArgs";
import { CarsFindManyArgs } from "./CarsFindManyArgs";
import { CarsFindUniqueArgs } from "./CarsFindUniqueArgs";
import { CreateCarsArgs } from "./CreateCarsArgs";
import { UpdateCarsArgs } from "./UpdateCarsArgs";
import { DeleteCarsArgs } from "./DeleteCarsArgs";
import { RentalsFindManyArgs } from "../../rentals/base/RentalsFindManyArgs";
import { Rentals } from "../../rentals/base/Rentals";
import { CarsService } from "../cars.service";
@graphql.Resolver(() => Cars)
export class CarsResolverBase {
  constructor(protected readonly service: CarsService) {}

  async _carsItemsMeta(
    @graphql.Args() args: CarsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Cars])
  async carsItems(@graphql.Args() args: CarsFindManyArgs): Promise<Cars[]> {
    return this.service.carsItems(args);
  }

  @graphql.Query(() => Cars, { nullable: true })
  async cars(@graphql.Args() args: CarsFindUniqueArgs): Promise<Cars | null> {
    const result = await this.service.cars(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Cars)
  async createCars(@graphql.Args() args: CreateCarsArgs): Promise<Cars> {
    return await this.service.createCars({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Cars)
  async updateCars(@graphql.Args() args: UpdateCarsArgs): Promise<Cars | null> {
    try {
      return await this.service.updateCars({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Cars)
  async deleteCars(@graphql.Args() args: DeleteCarsArgs): Promise<Cars | null> {
    try {
      return await this.service.deleteCars(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Rentals], { name: "rentalsItems" })
  async findRentalsItems(
    @graphql.Parent() parent: Cars,
    @graphql.Args() args: RentalsFindManyArgs
  ): Promise<Rentals[]> {
    const results = await this.service.findRentalsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
