/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RentalsService } from "../rentals.service";
import { RentalsCreateInput } from "./RentalsCreateInput";
import { Rentals } from "./Rentals";
import { RentalsFindManyArgs } from "./RentalsFindManyArgs";
import { RentalsWhereUniqueInput } from "./RentalsWhereUniqueInput";
import { RentalsUpdateInput } from "./RentalsUpdateInput";

export class RentalsControllerBase {
  constructor(protected readonly service: RentalsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rentals })
  async createRentals(
    @common.Body() data: RentalsCreateInput
  ): Promise<Rentals> {
    return await this.service.createRentals({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,

        car: data.car
          ? {
              connect: data.car,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        returnDate: true,
        rentalDate: true,

        customer: {
          select: {
            id: true,
          },
        },

        car: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Rentals] })
  @ApiNestedQuery(RentalsFindManyArgs)
  async rentalsItems(@common.Req() request: Request): Promise<Rentals[]> {
    const args = plainToClass(RentalsFindManyArgs, request.query);
    return this.service.rentalsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        returnDate: true,
        rentalDate: true,

        customer: {
          select: {
            id: true,
          },
        },

        car: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rentals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async rentals(
    @common.Param() params: RentalsWhereUniqueInput
  ): Promise<Rentals | null> {
    const result = await this.service.rentals({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        returnDate: true,
        rentalDate: true,

        customer: {
          select: {
            id: true,
          },
        },

        car: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rentals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRentals(
    @common.Param() params: RentalsWhereUniqueInput,
    @common.Body() data: RentalsUpdateInput
  ): Promise<Rentals | null> {
    try {
      return await this.service.updateRentals({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,

          car: data.car
            ? {
                connect: data.car,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          returnDate: true,
          rentalDate: true,

          customer: {
            select: {
              id: true,
            },
          },

          car: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rentals })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRentals(
    @common.Param() params: RentalsWhereUniqueInput
  ): Promise<Rentals | null> {
    try {
      return await this.service.deleteRentals({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          returnDate: true,
          rentalDate: true,

          customer: {
            select: {
              id: true,
            },
          },

          car: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
