/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Rentals as PrismaRentals,
  Customers as PrismaCustomers,
  Cars as PrismaCars,
} from "@prisma/client";

export class RentalsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RentalsCountArgs, "select">): Promise<number> {
    return this.prisma.rentals.count(args);
  }

  async rentalsItems(
    args: Prisma.RentalsFindManyArgs
  ): Promise<PrismaRentals[]> {
    return this.prisma.rentals.findMany(args);
  }
  async rentals(
    args: Prisma.RentalsFindUniqueArgs
  ): Promise<PrismaRentals | null> {
    return this.prisma.rentals.findUnique(args);
  }
  async createRentals(args: Prisma.RentalsCreateArgs): Promise<PrismaRentals> {
    return this.prisma.rentals.create(args);
  }
  async updateRentals(args: Prisma.RentalsUpdateArgs): Promise<PrismaRentals> {
    return this.prisma.rentals.update(args);
  }
  async deleteRentals(args: Prisma.RentalsDeleteArgs): Promise<PrismaRentals> {
    return this.prisma.rentals.delete(args);
  }

  async getCustomer(parentId: string): Promise<PrismaCustomers | null> {
    return this.prisma.rentals
      .findUnique({
        where: { id: parentId },
      })
      .customer();
  }

  async getCar(parentId: string): Promise<PrismaCars | null> {
    return this.prisma.rentals
      .findUnique({
        where: { id: parentId },
      })
      .car();
  }
}
