/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Rentals } from "./Rentals";
import { RentalsCountArgs } from "./RentalsCountArgs";
import { RentalsFindManyArgs } from "./RentalsFindManyArgs";
import { RentalsFindUniqueArgs } from "./RentalsFindUniqueArgs";
import { CreateRentalsArgs } from "./CreateRentalsArgs";
import { UpdateRentalsArgs } from "./UpdateRentalsArgs";
import { DeleteRentalsArgs } from "./DeleteRentalsArgs";
import { Customers } from "../../customers/base/Customers";
import { Cars } from "../../cars/base/Cars";
import { RentalsService } from "../rentals.service";
@graphql.Resolver(() => Rentals)
export class RentalsResolverBase {
  constructor(protected readonly service: RentalsService) {}

  async _rentalsItemsMeta(
    @graphql.Args() args: RentalsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Rentals])
  async rentalsItems(
    @graphql.Args() args: RentalsFindManyArgs
  ): Promise<Rentals[]> {
    return this.service.rentalsItems(args);
  }

  @graphql.Query(() => Rentals, { nullable: true })
  async rentals(
    @graphql.Args() args: RentalsFindUniqueArgs
  ): Promise<Rentals | null> {
    const result = await this.service.rentals(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rentals)
  async createRentals(
    @graphql.Args() args: CreateRentalsArgs
  ): Promise<Rentals> {
    return await this.service.createRentals({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,

        car: args.data.car
          ? {
              connect: args.data.car,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Rentals)
  async updateRentals(
    @graphql.Args() args: UpdateRentalsArgs
  ): Promise<Rentals | null> {
    try {
      return await this.service.updateRentals({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,

          car: args.data.car
            ? {
                connect: args.data.car,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Rentals)
  async deleteRentals(
    @graphql.Args() args: DeleteRentalsArgs
  ): Promise<Rentals | null> {
    try {
      return await this.service.deleteRentals(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Customers, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(
    @graphql.Parent() parent: Rentals
  ): Promise<Customers | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Cars, {
    nullable: true,
    name: "car",
  })
  async getCar(@graphql.Parent() parent: Rentals): Promise<Cars | null> {
    const result = await this.service.getCar(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
